apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: trend-cluster
  region: ap-south-1
  version: "1.33"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20