apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default   # change if you deploy in another namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbWFsaW5iaWNzIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9yMmRqM1JuckR4UnVYVzFSRThaTEZYZGJ2bkEiLCJlbWFpbCI6ImFtYWxpbmJpY3NAZ21haWwuY29tIiwiYXV0aCI6IllXMWhiR2x1WW1samN6cGtZMnR5WDNCaGRGOXlNbVJxTTFKdWNrUjRVblZZVnpGU1JUaGFURVpZWkdKMmJrRT0ifX19
